// Full list of active ISO 4217 currency codes that open.er-api.com (see
// utils/exchange-rates.ts) actually has rates for — every currency here must
// stay convertible, so this deliberately excludes codes with no rate data
// (currently just KPW, North Korean Won) rather than letting someone pick a
// currency an entry can never be converted from/to.
//
// `countryCode` is a lowercase ISO 3166-1 alpha-2 code used only to look up a
// flag image (see currency-picker.tsx), and is left undefined for currencies
// with no single representative country (the CFA franc zones, which have no
// official union flag the way the EU does for EUR).
export type Currency = {
  code: string;
  name: string;
  countryCode?: string;
};

export const CURRENCIES: Currency[] = [
  { code: "AED", name: "UAE Dirham", countryCode: "ae" },
  { code: "AFN", name: "Afghan Afghani", countryCode: "af" },
  { code: "ALL", name: "Albanian Lek", countryCode: "al" },
  { code: "AMD", name: "Armenian Dram", countryCode: "am" },
  { code: "ANG", name: "Netherlands Antillean Guilder", countryCode: "cw" },
  { code: "AOA", name: "Angolan Kwanza", countryCode: "ao" },
  { code: "ARS", name: "Argentine Peso", countryCode: "ar" },
  { code: "AUD", name: "Australian Dollar", countryCode: "au" },
  { code: "AWG", name: "Aruban Florin", countryCode: "aw" },
  { code: "AZN", name: "Azerbaijani Manat", countryCode: "az" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", countryCode: "ba" },
  { code: "BBD", name: "Barbadian Dollar", countryCode: "bb" },
  { code: "BDT", name: "Bangladeshi Taka", countryCode: "bd" },
  { code: "BGN", name: "Bulgarian Lev", countryCode: "bg" },
  { code: "BHD", name: "Bahraini Dinar", countryCode: "bh" },
  { code: "BIF", name: "Burundian Franc", countryCode: "bi" },
  { code: "BMD", name: "Bermudan Dollar", countryCode: "bm" },
  { code: "BND", name: "Brunei Dollar", countryCode: "bn" },
  { code: "BOB", name: "Bolivian Boliviano", countryCode: "bo" },
  { code: "BRL", name: "Brazilian Real", countryCode: "br" },
  { code: "BSD", name: "Bahamian Dollar", countryCode: "bs" },
  { code: "BTN", name: "Bhutanese Ngultrum", countryCode: "bt" },
  { code: "BWP", name: "Botswanan Pula", countryCode: "bw" },
  { code: "BYN", name: "Belarusian Ruble", countryCode: "by" },
  { code: "BZD", name: "Belize Dollar", countryCode: "bz" },
  { code: "CAD", name: "Canadian Dollar", countryCode: "ca" },
  { code: "CDF", name: "Congolese Franc", countryCode: "cd" },
  { code: "CHF", name: "Swiss Franc", countryCode: "ch" },
  { code: "CLP", name: "Chilean Peso", countryCode: "cl" },
  { code: "CNY", name: "Chinese Yuan", countryCode: "cn" },
  { code: "COP", name: "Colombian Peso", countryCode: "co" },
  { code: "CRC", name: "Costa Rican Colón", countryCode: "cr" },
  { code: "CUP", name: "Cuban Peso", countryCode: "cu" },
  { code: "CVE", name: "Cape Verdean Escudo", countryCode: "cv" },
  { code: "CZK", name: "Czech Koruna", countryCode: "cz" },
  { code: "DJF", name: "Djiboutian Franc", countryCode: "dj" },
  { code: "DKK", name: "Danish Krone", countryCode: "dk" },
  { code: "DOP", name: "Dominican Peso", countryCode: "do" },
  { code: "DZD", name: "Algerian Dinar", countryCode: "dz" },
  { code: "EGP", name: "Egyptian Pound", countryCode: "eg" },
  { code: "ERN", name: "Eritrean Nakfa", countryCode: "er" },
  { code: "ETB", name: "Ethiopian Birr", countryCode: "et" },
  { code: "EUR", name: "Euro", countryCode: "eu" },
  { code: "FJD", name: "Fijian Dollar", countryCode: "fj" },
  { code: "FKP", name: "Falkland Islands Pound", countryCode: "fk" },
  { code: "GBP", name: "British Pound", countryCode: "gb" },
  { code: "GEL", name: "Georgian Lari", countryCode: "ge" },
  { code: "GHS", name: "Ghanaian Cedi", countryCode: "gh" },
  { code: "GIP", name: "Gibraltar Pound", countryCode: "gi" },
  { code: "GMD", name: "Gambian Dalasi", countryCode: "gm" },
  { code: "GNF", name: "Guinean Franc", countryCode: "gn" },
  { code: "GTQ", name: "Guatemalan Quetzal", countryCode: "gt" },
  { code: "GYD", name: "Guyanaese Dollar", countryCode: "gy" },
  { code: "HKD", name: "Hong Kong Dollar", countryCode: "hk" },
  { code: "HNL", name: "Honduran Lempira", countryCode: "hn" },
  { code: "HTG", name: "Haitian Gourde", countryCode: "ht" },
  { code: "HUF", name: "Hungarian Forint", countryCode: "hu" },
  { code: "IDR", name: "Indonesian Rupiah", countryCode: "id" },
  { code: "ILS", name: "Israeli New Shekel", countryCode: "il" },
  { code: "INR", name: "Indian Rupee", countryCode: "in" },
  { code: "IQD", name: "Iraqi Dinar", countryCode: "iq" },
  { code: "IRR", name: "Iranian Rial", countryCode: "ir" },
  { code: "ISK", name: "Icelandic Króna", countryCode: "is" },
  { code: "JMD", name: "Jamaican Dollar", countryCode: "jm" },
  { code: "JOD", name: "Jordanian Dinar", countryCode: "jo" },
  { code: "JPY", name: "Japanese Yen", countryCode: "jp" },
  { code: "KES", name: "Kenyan Shilling", countryCode: "ke" },
  { code: "KGS", name: "Kyrgystani Som", countryCode: "kg" },
  { code: "KHR", name: "Cambodian Riel", countryCode: "kh" },
  { code: "KMF", name: "Comorian Franc", countryCode: "km" },
  { code: "KRW", name: "South Korean Won", countryCode: "kr" },
  { code: "KWD", name: "Kuwaiti Dinar", countryCode: "kw" },
  { code: "KYD", name: "Cayman Islands Dollar", countryCode: "ky" },
  { code: "KZT", name: "Kazakhstani Tenge", countryCode: "kz" },
  { code: "LAK", name: "Laotian Kip", countryCode: "la" },
  { code: "LBP", name: "Lebanese Pound", countryCode: "lb" },
  { code: "LKR", name: "Sri Lankan Rupee", countryCode: "lk" },
  { code: "LRD", name: "Liberian Dollar", countryCode: "lr" },
  { code: "LSL", name: "Lesotho Loti", countryCode: "ls" },
  { code: "LYD", name: "Libyan Dinar", countryCode: "ly" },
  { code: "MAD", name: "Moroccan Dirham", countryCode: "ma" },
  { code: "MDL", name: "Moldovan Leu", countryCode: "md" },
  { code: "MGA", name: "Malagasy Ariary", countryCode: "mg" },
  { code: "MKD", name: "Macedonian Denar", countryCode: "mk" },
  { code: "MMK", name: "Myanmar Kyat", countryCode: "mm" },
  { code: "MNT", name: "Mongolian Tugrik", countryCode: "mn" },
  { code: "MOP", name: "Macanese Pataca", countryCode: "mo" },
  { code: "MRU", name: "Mauritanian Ouguiya", countryCode: "mr" },
  { code: "MUR", name: "Mauritian Rupee", countryCode: "mu" },
  { code: "MVR", name: "Maldivian Rufiyaa", countryCode: "mv" },
  { code: "MWK", name: "Malawian Kwacha", countryCode: "mw" },
  { code: "MXN", name: "Mexican Peso", countryCode: "mx" },
  { code: "MYR", name: "Malaysian Ringgit", countryCode: "my" },
  { code: "MZN", name: "Mozambican Metical", countryCode: "mz" },
  { code: "NAD", name: "Namibian Dollar", countryCode: "na" },
  { code: "NGN", name: "Nigerian Naira", countryCode: "ng" },
  { code: "NIO", name: "Nicaraguan Córdoba", countryCode: "ni" },
  { code: "NOK", name: "Norwegian Krone", countryCode: "no" },
  { code: "NPR", name: "Nepalese Rupee", countryCode: "np" },
  { code: "NZD", name: "New Zealand Dollar", countryCode: "nz" },
  { code: "OMR", name: "Omani Rial", countryCode: "om" },
  { code: "PAB", name: "Panamanian Balboa", countryCode: "pa" },
  { code: "PEN", name: "Peruvian Sol", countryCode: "pe" },
  { code: "PGK", name: "Papua New Guinean Kina", countryCode: "pg" },
  { code: "PHP", name: "Philippine Peso", countryCode: "ph" },
  { code: "PKR", name: "Pakistani Rupee", countryCode: "pk" },
  { code: "PLN", name: "Polish Zloty", countryCode: "pl" },
  { code: "PYG", name: "Paraguayan Guarani", countryCode: "py" },
  { code: "QAR", name: "Qatari Rial", countryCode: "qa" },
  { code: "RON", name: "Romanian Leu", countryCode: "ro" },
  { code: "RSD", name: "Serbian Dinar", countryCode: "rs" },
  { code: "RUB", name: "Russian Ruble", countryCode: "ru" },
  { code: "RWF", name: "Rwandan Franc", countryCode: "rw" },
  { code: "SAR", name: "Saudi Riyal", countryCode: "sa" },
  { code: "SBD", name: "Solomon Islands Dollar", countryCode: "sb" },
  { code: "SCR", name: "Seychellois Rupee", countryCode: "sc" },
  { code: "SDG", name: "Sudanese Pound", countryCode: "sd" },
  { code: "SEK", name: "Swedish Krona", countryCode: "se" },
  { code: "SGD", name: "Singapore Dollar", countryCode: "sg" },
  { code: "SHP", name: "Saint Helena Pound", countryCode: "sh" },
  { code: "SLE", name: "Sierra Leonean Leone", countryCode: "sl" },
  { code: "SOS", name: "Somali Shilling", countryCode: "so" },
  { code: "SRD", name: "Surinamese Dollar", countryCode: "sr" },
  { code: "SSP", name: "South Sudanese Pound", countryCode: "ss" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", countryCode: "st" },
  { code: "SYP", name: "Syrian Pound", countryCode: "sy" },
  { code: "SZL", name: "Swazi Lilangeni", countryCode: "sz" },
  { code: "THB", name: "Thai Baht", countryCode: "th" },
  { code: "TJS", name: "Tajikistani Somoni", countryCode: "tj" },
  { code: "TMT", name: "Turkmenistani Manat", countryCode: "tm" },
  { code: "TND", name: "Tunisian Dinar", countryCode: "tn" },
  { code: "TOP", name: "Tongan Pa'anga", countryCode: "to" },
  { code: "TRY", name: "Turkish Lira", countryCode: "tr" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", countryCode: "tt" },
  { code: "TWD", name: "New Taiwan Dollar", countryCode: "tw" },
  { code: "TZS", name: "Tanzanian Shilling", countryCode: "tz" },
  { code: "UAH", name: "Ukrainian Hryvnia", countryCode: "ua" },
  { code: "UGX", name: "Ugandan Shilling", countryCode: "ug" },
  { code: "USD", name: "US Dollar", countryCode: "us" },
  { code: "UYU", name: "Uruguayan Peso", countryCode: "uy" },
  { code: "UZS", name: "Uzbekistani Som", countryCode: "uz" },
  { code: "VES", name: "Venezuelan Bolívar", countryCode: "ve" },
  { code: "VND", name: "Vietnamese Dong", countryCode: "vn" },
  { code: "VUV", name: "Vanuatu Vatu", countryCode: "vu" },
  { code: "WST", name: "Samoan Tala", countryCode: "ws" },
  { code: "XAF", name: "Central African CFA Franc" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "XPF", name: "CFP Franc" },
  { code: "YER", name: "Yemeni Rial", countryCode: "ye" },
  { code: "ZAR", name: "South African Rand", countryCode: "za" },
  { code: "ZMW", name: "Zambian Kwacha", countryCode: "zm" },
  { code: "ZWL", name: "Zimbabwean Dollar", countryCode: "zw" },
];

export function findCurrency(code: string): Currency | undefined {
  return CURRENCIES.find((currency) => currency.code === code);
}

export function findCurrencyByCountryCode(countryCode: string): Currency | undefined {
  const normalized = countryCode.toLowerCase();
  return CURRENCIES.find((currency) => currency.countryCode === normalized);
}
